# Configuration file for custom scenarios for `premise`

---

production pathways:
  cement_SlagClinker:
    production volume:
      variable: Share|cement_SlagClinker
    ecoinvent alias:
      name: cement production, CEM II/A-V
      reference product: cement production, CEM II/A-V
      exists in original database: False

  cement_ClayClinker:
    production volume:
      variable: Share|cement_ClayClinker
    ecoinvent alias:
      name: cement production, Clay
      reference product: cement production, Clay
      exists in original database: False

  cement_FlyAshClinker:
    production volume:
      variable: Share|cement_FlyAshClinker
    ecoinvent alias:
      name: cement production, CEM II/A-S
      reference product: cement production, CEM II/A-S
      exists in original database: False

  cement_Clinker:
    production volume:
      variable: Share|cement_Clinker
    ecoinvent alias:
      name: market for cement, Portland
      reference product: cement, Portland
      
  cement_CEM_IIIA:
    production volume:
      variable: Share|cement_CEM_IIIA
    ecoinvent alias:
      name: market for cement, CEM III/A
      reference product: cement, CEM III/A

  cement_CEM_IIIB:
    production volume:
      variable: Share|cement_CEM_IIIB
    ecoinvent alias:
      name: market for cement, CEM III/B
      reference product: cement, CEM III/B
      
  cement_CEM_IIIC:
    production volume:
      variable: Share|cement_CEM_IIIC
    ecoinvent alias:
      name: market for cement, CEM III/C
      reference product: cement, CEM III/C
      
  cement_CEM_IVA:
    production volume:
      variable: Share|cement_CEM_IVA
    ecoinvent alias:
      name: market for cement, CEM IV/A
      reference product: cement, CEM IV/A

  cement_CEM_IVB:
    production volume:
      variable: Share|cement_CEM_IVB
    ecoinvent alias:
      name: market for cement, CEM IV/B
      reference product: cement, CEM IV/B
           
  cement_CEM_VA:
    production volume:
      variable: Share|cement_CEM_VA
    ecoinvent alias:
      name: market for cement, CEM V/A
      reference product: cement, CEM V/A

  cement_CEM_VB:
    production volume:
      variable: Share|cement_CEM_VB
    ecoinvent alias:
      name: market for cement, CEM V/B
      reference product: cement, CEM V/B
      
  steel_BOF:
    production volume:
      variable: Share|steel_BOF
    ecoinvent alias:
      name: steel production, converter, low-alloyed
      reference product: steel, low-alloyed

  steel_EAF:
    production volume:
      variable: Share|steel_EAF
    ecoinvent alias:
      name: steel production, electric, low-alloyed
      reference product: steel, low-alloyed
      
      

markets:
  - name: market for cement, all types, adjusted
    reference product: cement, all types
    unit: kilogram
    includes:
      - cement_SlagClinker
      - cement_ClayClinker
      - cement_FlyAshClinker
      - cement_Clinker
      - cement_CEM_IIIA
      - cement_CEM_IIIB
      - cement_CEM_IIIC
      - cement_CEM_IVA
      - cement_CEM_IVB
      - cement_CEM_VA
      - cement_CEM_VB

    replaces:
      - name: cement, all types to generic market for cement, unspecified
        product: cement, unspecified
        operator: equals
        
  - name: steel production, low-alloyed, adjusted
    reference product: steel, all types
    unit: kilogram
    includes:
      - steel_BOF
      - steel_EAF

    replaces:
      - name: market for steel, low-alloyed
        product: steel, low-alloyed
        operator: equals